-- MySQL Script generated by MySQL Workbench
-- Wed Mar  8 17:16:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema watchDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema watchDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `watchDB` DEFAULT CHARACTER SET utf8 ;
USE `watchDB` ;

-- -----------------------------------------------------
-- Table `watchDB`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watchDB`.`Customers` (
  `CustomerId` INT NOT NULL AUTO_INCREMENT,
  `CFirstName` VARCHAR(45) NULL,
  `CLastName` VARCHAR(45) NULL,
  `CUsername` VARCHAR(45) NOT NULL,
  `CPassword` VARCHAR(45) NOT NULL,
  `CEmail` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CustomerId`),
  UNIQUE INDEX `CustomerId_UNIQUE` (`CustomerId` ASC) VISIBLE,
  UNIQUE INDEX `CUsername_UNIQUE` (`CUsername` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watchDB`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watchDB`.`Admins` (
  `AdminId` INT NOT NULL AUTO_INCREMENT,
  `AUsername` VARCHAR(45) NULL,
  `APassword` VARCHAR(45) NULL,
  PRIMARY KEY (`AdminId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watchDB`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watchDB`.`Products` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `ProductDescription` VARCHAR(5000) NULL,
  `Stock` INT NOT NULL DEFAULT 0,
  `Image` VARCHAR(200) NULL DEFAULT 'https://130.290.200.109/defaultImage',
  `ProductName` VARCHAR(200) NOT NULL DEFAULT 'Watch',
  `Price` DECIMAL(10,2) NOT NULL,
  `IsVisible` BIT(1) NOT NULL DEFAULT 1,
  `Grade` DECIMAL(10,9) NOT NULL DEFAULT 0,
  `Gradees` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ProductId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watchDB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watchDB`.`Orders` (
  `OrderNr` INT NOT NULL AUTO_INCREMENT,
  `CId` INT NULL,
  `PId` INT NOT NULL,
  `BatchId` INT NOT NULL,
  `Amount` INT NOT NULL,
  `DeliveryAdress` VARCHAR(99) NOT NULL,
  `DeliveryName` VARCHAR(150) NOT NULL,
  `OrderPrice` DECIMAL(16,2) NOT NULL,
  PRIMARY KEY (`OrderNr`, `PId`),
  INDEX `CustomerId_idx` (`CId` ASC) VISIBLE,
  INDEX `Pid_idx` (`PId` ASC) VISIBLE,
  CONSTRAINT `CId`
    FOREIGN KEY (`CId`)
    REFERENCES `watchDB`.`Customers` (`CustomerId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Pid`
    FOREIGN KEY (`PId`)
    REFERENCES `watchDB`.`Products` (`ProductId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watchDB`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watchDB`.`Cart` (
  `ItemId` INT NOT NULL AUTO_INCREMENT,
  `CartCId` INT NOT NULL,
  `CartPId` INT NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`ItemId`),
  INDEX `CId_idx` (`CartCId` ASC) VISIBLE,
  INDEX `PId_idx` (`CartPId` ASC) VISIBLE,
  CONSTRAINT `CartCId`
    FOREIGN KEY (`CartCId`)
    REFERENCES `watchDB`.`Customers` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CartPId`
    FOREIGN KEY (`CartPId`)
    REFERENCES `watchDB`.`Products` (`ProductId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watchDB`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watchDB`.`Comments` (
  `CommentId` INT NOT NULL AUTO_INCREMENT,
  `CustomerId` INT NOT NULL,
  `ProductId` INT NOT NULL,
  `Content` VARCHAR(1000) NOT NULL DEFAULT 'Comment',
  PRIMARY KEY (`CommentId`),
  INDEX `CustomerId_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `ProductId_idx` (`ProductId` ASC) VISIBLE,
  CONSTRAINT `CustomerId`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `watchDB`.`Customers` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProductId`
    FOREIGN KEY (`ProductId`)
    REFERENCES `watchDB`.`Products` (`ProductId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
