-- MySQL Script generated by MySQL Workbench
-- Mon Jan 30 14:24:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `CustomerId` INT NOT NULL AUTO_INCREMENT,
  `CFirstName` VARCHAR(45) NULL,
  `CLastName` VARCHAR(45) NULL,
  `CUsername` VARCHAR(45) NOT NULL,
  `CPassword` VARCHAR(45) NOT NULL,
  `CEmail` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CustomerId`),
  UNIQUE INDEX `CustomerId_UNIQUE` (`CustomerId` ASC) VISIBLE,
  UNIQUE INDEX `CUsername_UNIQUE` (`CUsername` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admins` (
  `AdminId` INT NOT NULL,
  `AUsername` VARCHAR(45) NULL,
  `APassword` VARCHAR(45) NULL,
  PRIMARY KEY (`AdminId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `ProductDescription` VARCHAR(5000) NULL,
  `Stock` INT NOT NULL DEFAULT 0,
  `Image` VARCHAR(200) NULL DEFAULT 'https://130.290.200.109/defaultImage',
  `ProductName` VARCHAR(200) NOT NULL DEFAULT 'Watch',
  PRIMARY KEY (`ProductId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `OrderNr` INT NOT NULL AUTO_INCREMENT,
  `CId` INT NOT NULL,
  `PId` INT NOT NULL,
  `Amount` VARCHAR(45) NOT NULL,
  `DeliveryAdress` VARCHAR(99) NOT NULL,
  PRIMARY KEY (`OrderNr`, `PId`),
  INDEX `CustomerId_idx` (`CId` ASC) VISIBLE,
  INDEX `Pid_idx` (`PId` ASC) VISIBLE,
  CONSTRAINT `CId`
    FOREIGN KEY (`CId`)
    REFERENCES `mydb`.`Customers` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `Pid`
    FOREIGN KEY (`PId`)
    REFERENCES `mydb`.`Products` (`ProductId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
